# services:
#   server:
#     build:
#       context: .
#     environment:
#       NODE_ENV: production
#     ports:
#       - 8081:8081

services:
  react_native_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=10.0.0.19
    ports:
      - '8081:8081'
    volumes:
      - .:/app
    tty: true
    command: sh -c "npm install && npx expo start --web"
